// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinalAplicada.DAL;

#nullable disable

namespace ProyectoFinalAplicada.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ProyectoFinalAplicada.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Admin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidoAdmin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContrasenaAdmin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreAdmin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoAdmin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Admin");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.Cliente", b =>
                {
                    b.Property<int>("Id_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CalleCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContrasenaCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumViviendaCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Cliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.Entrada", b =>
                {
                    b.Property<int>("Id_Entrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefFactura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Entrada");

                    b.ToTable("Entrada");
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.Pedido", b =>
                {
                    b.Property<int>("Id_Pedido")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<bool>("Deliveri")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("TEXT");

                    b.Property<double>("MontoTotal")
                        .HasColumnType("REAL");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefSitio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Pedido");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.Producto", b =>
                {
                    b.Property<int>("Id_Producto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PrecioCompra")
                        .HasColumnType("REAL");

                    b.Property<double>("PrecioVenta")
                        .HasColumnType("REAL");

                    b.Property<string>("TipoVenta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Producto");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.Proveedor", b =>
                {
                    b.Property<int>("Id_Proveedor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoProveedor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Proveedor");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("Id_Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Tipo");

                    b.ToTable("CategoriaProducto");
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.Transferencia", b =>
                {
                    b.Property<int>("Id_Transferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaTransferencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumTransferencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Transferencia");

                    b.ToTable("Transferencia");
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.Pedido", b =>
                {
                    b.HasOne("ProyectoFinalAplicada.Models.Transferencia", null)
                        .WithMany("DetalleTransferencia")
                        .HasForeignKey("Id_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.Producto", b =>
                {
                    b.HasOne("ProyectoFinalAplicada.Models.Pedido", null)
                        .WithMany("DetallePedido")
                        .HasForeignKey("Id_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinalAplicada.Models.CategoriaProducto", null)
                        .WithMany("DetalleTipo")
                        .HasForeignKey("Id_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.Proveedor", b =>
                {
                    b.HasOne("ProyectoFinalAplicada.Models.Entrada", null)
                        .WithMany("DetalleEntrada")
                        .HasForeignKey("Id_Proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.CategoriaProducto", b =>
                {
                    b.HasOne("ProyectoFinalAplicada.Models.Proveedor", null)
                        .WithMany("ProveedorDetalle")
                        .HasForeignKey("Id_Tipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.Entrada", b =>
                {
                    b.Navigation("DetalleEntrada");
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.Pedido", b =>
                {
                    b.Navigation("DetallePedido");
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.Proveedor", b =>
                {
                    b.Navigation("ProveedorDetalle");
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.CategoriaProducto", b =>
                {
                    b.Navigation("DetalleTipo");
                });

            modelBuilder.Entity("ProyectoFinalAplicada.Models.Transferencia", b =>
                {
                    b.Navigation("DetalleTransferencia");
                });
#pragma warning restore 612, 618
        }
    }
}
